artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Aman123lug/End-to-End chicken-diesase-implementation/data/Chicken-fecal-images
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
